_wandb:
    value:
        cli_version: 0.23.0
        e:
            rb4puj7d8wn5sfd5s2k27fojfof4dewr:
                args:
                    - --data_path
                    - ..experiment/dataset/ETTh1.csv
                    - --model_name
                    - PatchTST
                    - --use_wandb
                codePath: src/main.py
                codePathLocal: src/main.py
                email: tonyxia777@gmail.com
                executable: /home/ubuntu/miniconda3/envs/tsfm-bench/bin/python
                host: jupyterhub-singleuser-instance-txia
                os: Linux-6.8.0-106-generic-x86_64-with-glibc2.27
                program: /home/ubuntu/TSA/src/main.py
                python: CPython 3.10.18
                root: /home/ubuntu/TSA
                startedAt: "2026-04-08T14:18:59.269840Z"
                writerId: rb4puj7d8wn5sfd5s2k27fojfof4dewr
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.10.18
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
attack_method:
    value: TSA
batch_size:
    value: 32
data_path:
    value: ..experiment/dataset/ETTh1.csv
epsilon:
    value: 0.1
max_batches:
    value: 0
model_name:
    value: PatchTST
pred_len:
    value: 48
project_name:
    value: TSFM-Robustness
seq_len:
    value: 96
tau:
    value: 9
use_wandb:
    value: true
